# This workflow will deploy the app to github pages.

name: CD

on:
  push:
    branches: [ master ]

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Set up node environment
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install packages
        run: npm install

      - name: Compile TS and Package
        run: npm run build-linux

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./dist
